# Credenciales de Mailtrap
# Configura tus propias credenciales aquí
mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=efe37899ca9f04
mail.password=f6a3859a59a770
mail.from=no-reply@concursos.com