# Credenciales de Mailtrap
# Configura aca las credenciales
# luego renombra el archivo a mail.properties
# termina moviendo el archivo a src/main/resources
mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=15b50adc0cefcb
mail.password=56d678bf9b8ada



